CREATE TABLE PAIS(
    ID_PAIS NUMBER PRIMARY KEY,
    nome VARCHAR(20)
)



CREATE TABLE ESTADO(
    ID_ESTADO NUMBER PRIMARY KEY,
    nome VARCHAR(30),
    ID_PAIS NUMBER
)

DROP TABLE ESTADO;

CREATE TABLE CIDADE(
    ID_ESTADO NUMBER PRIMARY KEY,
    cidade VARCHAR(30),
    ID_PAIS NUMBER
)

SELECT * FROM ESTADO;

INSERT INTO PAIS (ID_PAIS, nome) VALUES (1,'Brasil');
INSERT INTO ESTADO(ID_ESTADO,nome, ID_PAIS) VALUES (1,'Bahia',1);
SELECT * FROM PAIS;